version: "3"

services:
  nats-server:
    image: nats:latest

  client-gateway:
    image: client-gateway-prod
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${GATEWAY_CLIENT_PORT}:${GATEWAY_CLIENT_PORT}
    environment:
      - PORT=${GATEWAY_CLIENT_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    image: auth-ms-prod
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=4001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}
      - JWT_EXPIRES_IN=${AUTH_JWT_EXPIRES_IN}

  products-ms:
    image: products-ms-prod
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=4002
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222
  # ==================
  # Payment Microservice
  # ==================
  payments-ms:
    image: payments-ms-prod
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
    environment:
      - PORT=${PAYMENT_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WH_SECRET=${STRIPE_WH_SECRET}

  orders-ms:
    image: orders-ms-prod
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DB_URL=${ORDERS_DB_URL}
    restart: always
    environment:
      - PORT=4003
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DB_URL}
