version: "3"

services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"

  client-gateway:
    build: ./client-gateway
    ports:
      - ${GATEWAY_CLIENT_PORT}:4000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev

  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev

  orders-ms:
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    restart: always
    depends_on:
      - orders-db

  orders-db:
    image: postgres:16.2
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ordersdb
